import type { Metadata } from "next"
import { Lato } from "next/font/google"
import "./globals.css"
import { Header } from "./(components)/Header"

const lato = Lato({
  variable: "--font-lato",
  weight: ["400", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Jéssica Birck | Advogada",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
