import type { Metadata } from "next"
import { Crimson_Pro, Lato } from "next/font/google"
import "./globals.css"
import { Header } from "./(components)/Header"

const lato = Lato({
  variable: "--font-lato",
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
})

const crimsonPro = Crimson_Pro({
  variable: "--font-crimson",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Jéssica Birck | Advogada",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${lato.variable} ${crimsonPro.variable}`}
      data-scroll-behavior="smooth"
    >
      <body suppressHydrationWarning>
        <Header />
        {children}
      </body>
    </html>
  )
}
